<a href="https://colab.research.google.com/github/TBKHori/A.I_ARU/blob/main/Numpy_ARU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Create a list.
my_list = [100, 300, 500, 700, 900]
my_list

[100, 300, 500, 700, 900]

In [ ]:
#Use the list to initialise a numpy array.
np.array(my_list)

array([100, 300, 500, 700, 900])

In [ ]:
# Create a list of lists
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# Initalise the array with the list of lists.
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Note the end item is excluded.
np.arange(100,110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [ ]:
# Using negative step factor gives a decreasing sequence.
np.arange(20,1,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
# Generate 1-d array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# A 2-d array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Generate the 1-d array of ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# 2-d array of ones.
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Generate ten elements between 0 and 100
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# Method can be used to generate finer granular sequence
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
# Create a Identity matrix of size 3X3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Generate a random number array from uniform distribution in the interval [0,1].
np.random.rand(5)

array([0.0731552 , 0.69598293, 0.60611053, 0.53666673, 0.72866187])

In [ ]:
# Generate a 2-d array of random numbers
np.random.rand(5,5)

array([[0.66937586, 0.03978199, 0.8360727 , 0.48342275, 0.88405642],
       [0.60302979, 0.24611467, 0.91390779, 0.4993939 , 0.8617712 ],
       [0.88844509, 0.15871527, 0.67286544, 0.65613974, 0.17915326],
       [0.37895443, 0.07724579, 0.46544209, 0.28358995, 0.83338673],
       [0.49775974, 0.88999047, 0.4954952 , 0.41143846, 0.46744953]])

In [ ]:
# Generates a 1-d random sequence from normal distribution.
np.random.randn(4)

array([0.69804738, 0.05828051, 0.5300142 , 3.21067839])

In [ ]:
# Generates a 2-d random array from a normal distribution.
np.random.randn(5,5)

array([[-1.10877657,  0.92046652, -0.39017978, -1.32952024,  0.87992697],
       [ 1.42723675,  0.73646703,  1.0190623 , -1.20631558,  0.30227932],
       [ 0.06847157,  1.40331149, -0.45962369,  1.52641378, -0.07122538],
       [ 1.84890838,  1.51953051, -0.35991742,  2.13844903,  0.27621238],
       [-1.16895391, -0.88207311, -0.23688812, -0.70399737, -2.07001873]])

In [ ]:
# Generate a single random integer between 1 and 100.
np.random.randint(1,100)

72

In [ ]:
# Generate a sequence of random numbers between 1 and 100
np.random.randint(1,100,10)

array([81, 95, 39, 68, 53, 42, 52, 20, 71, 25])

In [ ]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create an array of 10 ones 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Create an array of all the even integers from 10 to 50
np.linspace(10,50,21)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])