<a href="https://colab.research.google.com/github/TBKHori/A.I_ARU/blob/main/Numpy_ARU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Create a list.
my_list = [100, 300, 500, 700, 900]
my_list

[100, 300, 500, 700, 900]

In [ ]:
#Use the list to initialise a numpy array.
np.array(my_list)

array([100, 300, 500, 700, 900])

In [ ]:
# Create a list of lists
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# Initalise the array with the list of lists.
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Note the end item is excluded.
np.arange(100,110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [ ]:
# Using negative step factor gives a decreasing sequence.
np.arange(20,1,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
# Generate 1-d array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# A 2-d array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Generate the 1-d array of ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# 2-d array of ones.
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Generate ten elements between 0 and 100
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# Method can be used to generate finer granular sequence
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
# Create a Identity matrix of size 3X3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Generate a random number array from uniform distribution in the interval [0,1].
np.random.rand(5)

array([0.0731552 , 0.69598293, 0.60611053, 0.53666673, 0.72866187])

In [ ]:
# Generate a 2-d array of random numbers
np.random.rand(5,5)

array([[0.66937586, 0.03978199, 0.8360727 , 0.48342275, 0.88405642],
       [0.60302979, 0.24611467, 0.91390779, 0.4993939 , 0.8617712 ],
       [0.88844509, 0.15871527, 0.67286544, 0.65613974, 0.17915326],
       [0.37895443, 0.07724579, 0.46544209, 0.28358995, 0.83338673],
       [0.49775974, 0.88999047, 0.4954952 , 0.41143846, 0.46744953]])

In [ ]:
# Generates a 1-d random sequence from normal distribution.
np.random.randn(4)

array([0.69804738, 0.05828051, 0.5300142 , 3.21067839])

In [ ]:
# Generates a 2-d random array from a normal distribution.
np.random.randn(5,5)

array([[-1.10877657,  0.92046652, -0.39017978, -1.32952024,  0.87992697],
       [ 1.42723675,  0.73646703,  1.0190623 , -1.20631558,  0.30227932],
       [ 0.06847157,  1.40331149, -0.45962369,  1.52641378, -0.07122538],
       [ 1.84890838,  1.51953051, -0.35991742,  2.13844903,  0.27621238],
       [-1.16895391, -0.88207311, -0.23688812, -0.70399737, -2.07001873]])

In [ ]:
# Generate a single random integer between 1 and 100.
np.random.randint(1,100)

72

In [ ]:
# Generate a sequence of random numbers between 1 and 100
np.random.randint(1,100,10)

array([81, 95, 39, 68, 53, 42, 52, 20, 71, 25])

In [ ]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create an array of 10 ones 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Create an array of all the even integers from 10 to 50
np.linspace(10,50,21)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Use NumPy to generate a random number between 0 and 1
np.random.rand(1, 1)

array([[0.4123168]])

In [ ]:
""" Use NumPy to generate an array of 25 random numbers sampled from a standard normal dis-
tribution """
np.random.randn(5,5)

array([[-2.32507069, -0.81707973,  0.93223028, -0.34660978, -1.14373342],
       [-0.90209063, -0.50446616,  0.01697685, -0.32603256, -0.6962793 ],
       [ 0.066814  ,  0.06032784,  0.12993409,  0.10870005,  0.09252807],
       [-1.27792331,  0.64480548,  1.71225714,  1.44488986, -2.92113157],
       [ 2.79235094,  0.1135398 , -1.58660665, -0.00604169,  1.0451334 ]])

In [ ]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
# Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])