<a href="https://colab.research.google.com/github/TBKHori/A.I_ARU/blob/main/RedWineQualityAnalysis_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Load the wineQuelityReds.csv file into a numpy array!
warr = np.genfromtxt('wineQualityReds.csv',skip_header=1,delimiter=',')
warr

array([[1.000e+00, 7.400e+00, 7.000e-01, ..., 5.600e-01, 9.400e+00,
        5.000e+00],
       [2.000e+00, 7.800e+00, 8.800e-01, ..., 6.800e-01, 9.800e+00,
        5.000e+00],
       [3.000e+00, 7.800e+00, 7.600e-01, ..., 6.500e-01, 9.800e+00,
        5.000e+00],
       ...,
       [1.597e+03, 6.300e+00, 5.100e-01, ..., 7.500e-01, 1.100e+01,
        6.000e+00],
       [1.598e+03, 5.900e+00, 6.450e-01, ..., 7.100e-01, 1.020e+01,
        5.000e+00],
       [1.599e+03, 6.000e+00, 3.100e-01, ..., 6.600e-01, 1.100e+01,
        6.000e+00]])

In [ ]:
# what datatype is this numpy array?
# warr.dtype
type(warr[0,0])

numpy.float64

In [ ]:
# How many data points and features does this data contain?
warr.shape

(1599, 13)

In [ ]:
# What are the features available?.
warr[0:10, :]

array([[1.000e+00, 7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02,
        1.100e+01, 3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00,
        5.000e+00],
       [2.000e+00, 7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02,
        2.500e+01, 6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00,
        5.000e+00],
       [3.000e+00, 7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02,
        1.500e+01, 5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00,
        5.000e+00],
       [4.000e+00, 1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02,
        1.700e+01, 6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00,
        6.000e+00],
       [5.000e+00, 7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02,
        1.100e+01, 3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00,
        5.000e+00],
       [6.000e+00, 7.400e+00, 6.600e-01, 0.000e+00, 1.800e+00, 7.500e-02,
        1.300e+01, 4.000e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00,
        5.00

In [ ]:
# Create another array of feature names
ft_name = np.genfromtxt('wineQualityReds.csv',skip_header=0,delimiter=',',dtype=str)[0]
ft_name

array(['', 'fixed.acidity', 'volatile.acidity', 'citric.acid',
       'residual.sugar', 'chlorides', 'free.sulfur.dioxide',
       'total.sulfur.dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'], dtype='<U20')

In [ ]:
# Find the wine ids as integer
warr[:,0].astype(int)

array([-2147483648,           1,           2, ...,        1597,
              1598,        1599])

In [ ]:
# Convert the whole array into integer datatype using astype()